parameters: {}
environment:
    MONG_USER: admin
    MONG_PASSWORD: iiNPfMdU1fG3EGHc
    MONGO_HOST: cluster0.igt0g.mongodb.net

packages:
    - name: main
      parameters: {}
      environment: {}
      annotations: {}
      functions:
          - name: index
            binary: false
            main: ""
            runtime: nodejs:18
            web: true
            parameters: {}
            environment: {}
            annotations: {}
            limits: {}
