parameters: {}

packages:
    - name: main
      parameters: {}
      environment:
          MONGO_USERNAME: admin
          MONGO_PASSWORD: iiNPfMdU1fG3EGHc
          MONGO_HOST: cluster0.igt0g.mongodb.net
          MONGO_DATABASE: db
      annotations: {}
      functions:
          - name: index
            binary: false
            main: ""
            runtime: nodejs:18
            web: true
            parameters: {}
            environment: {}
            annotations: {}
            limits: {}
