@baseUrl = https://faas-ams3-2a2df116.doserverless.co/api/v1/web/fn-8b5106d1-8570-4f63-a2af-01748ac110f3/main
@apiKey = r_d_25c9dd62-ba12-44de-b303-67ef659ba7bd
@contentType = application/json

### Auth Login
# @name login
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "auth_login",
    "data": {
        "username": "admin",
        "api_key": "{{apiKey}}"
    }
}

### Get All Aspects
# @name getAspects
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "aspect_get_aspects",
    "data": []
}

### Create Single Aspect
# @name createAspect
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "aspect_insert_aspect",
    "data": {
        "tier": 1,
        "weight": 0.3,
        "potency": 0,
        "rune_ids": [0],
        "required_rune_ids": [],
        "blocked_aspect_ids": []
    }
}

### Create Multiple Aspects
# @name createAspects
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "aspect_insert_aspects",
    "data": [
        {
            "tier": 1,
            "weight": 0.3,
            "potency": 0,
            "rune_ids": [0],
            "required_rune_ids": [],
            "blocked_aspect_ids": []
        },
        {
            "tier": 1,
            "weight": 0.3,
            "potency": 10,
            "rune_ids": [0],
            "required_rune_ids": [],
            "blocked_aspect_ids": []
        }
    ]
}

### Update Single Aspect
# @name updateAspect
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "aspect_update_aspect",
    "data": {
        "aspect_id": 0,
        "potency": 10
    }
}

### Update Multiple Aspects
# @name updateAspects
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "aspect_update_aspects",
    "data": [
        {
            "aspect_id": 0,
            "potency": 0
        }
    ]
}

### Delete Single Aspect
# @name deleteAspect
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "aspect_delete_aspect",
    "data": {
        "aspect_id": 0
    }
}

### Delete Multiple Aspects
# @name deleteAspects
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "aspect_delete_aspects",
    "data": [
        { "aspect_id": 0 },
        { "aspect_id": 1 },
        { "aspect_id": 2 }
    ]
}

### Get All Runes
# @name getRunes
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "rune_get_runes",
    "data": []
}

### Get Single Rune by id rune_id 0
# @name getRuneById
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "rune_get_runes",
    "data": [{ "rune_id": 0 }]
}

### Create Single Rune
# @name createRune
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "rune_insert_rune",
    "data": {
        "name": "PHYSICAL",
        "weight": 1.0
    }
}

### Create Multiple Runes
# @name createRunes
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "rune_insert_runes",
    "data": [
        { "name": "PHYSICAL", "weight": 1.0 },
        { "name": "MAGICAL", "weight": 1.0 },
        { "name": "MELEE", "weight": 1.0 }
    ]
}

### Update Single Rune
# @name updateRune
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "rune_update_rune",
    "data": {
        "rune_id": 2,
        "weight": 0.3,
        "type": 0
    }
}

### Update Multiple Runes
# @name updateRunes
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "rune_update_runes",
    "data": [
        {
            "name": "PHYSICAL",
            "weight": 1,
            "type": 0
        },
        {
            "name": "MAGICAL",
            "weight": 1,
            "type": 0
        },
        {
            "rune_id": 2,
            "weight": 0.5,
            "type": 0
        }
    ]
}

### Delete Single Rune
# @name deleteRune
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "rune_delete_rune",
    "data": {
        "name": "PHYSICAL"
    }
}

### Delete Multiple Runes
# @name deleteRunes
POST {{baseUrl}}/index HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
    "api_key": "{{apiKey}}",
    "action": "rune_delete_runes",
    "data": [
        { "name": "PHYSICAL" },
        { "name": "MAGICAL" },
        { "name": "MELEE" }
    ]
} 