name: Run publish script on push

on: [push]

env:
    DOCTL_NAMESPACE: rune-dictionary

jobs:
    build:
        if: true
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Cache Bun modules
              uses: actions/cache@v3
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

            - name: Authenticate doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DO_API_KEY}}

            - name: Install doctl serverless support
              run: doctl serverless install

            - name: Install docts globally
              run: bunx -y docts-cli@latest --version && npm install -g docts-cli

            - name: Connect doctl serverless to functions namespace
              run: doctl serverless connect ${{ env.DOCTL_NAMESPACE }}

            - name: Install dependencies
              run: bun install

            - name: Run build script
              run: bun run build

            - name: Run deploy script
              run: bun run deploy

            - name: Verify deployment
              run: |
                  echo "Deployment completed"
